<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fa fa-lock login-icon-lock</name>
   <tag></tag>
   <elementGuidId>f5e552f0-d46d-4999-ae9d-c78efdc7481e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-lock.login-icon-lock</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login-form']/div[6]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1fea0d27-3479-4d95-bf3a-4ab786fc1db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-lock login-icon-lock</value>
      <webElementGuid>dae79c99-2256-4c57-af68-e1ebd9929f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form&quot;)/div[@class=&quot;col-md-12 login-input-text&quot;]/i[@class=&quot;fa fa-lock login-icon-lock&quot;]</value>
      <webElementGuid>ac0b477f-173b-41c9-92ed-674dd640cd8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div[6]/i</value>
      <webElementGuid>248dce1d-56b2-490c-ad7b-50070abe8a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/i</value>
      <webElementGuid>900a60ac-6c6e-461b-b381-ea247a5a9c42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
