<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>54fce651-5647-4e74-ac21-5501a2bfe25e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-xs-6.have-account-text.padding-login-link > center > a.login-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick=&quot;redirect_overlay('https://stage.mobipaid.com/login')&quot;])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81e34e63-f15a-498c-a4d6-ac51e27b6e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>redirect_overlay('https://stage.mobipaid.com/login')</value>
      <webElementGuid>c2905760-5126-4654-ab12-880d08505b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-link</value>
      <webElementGuid>e61f4cd8-ff87-4036-aa0a-f3f0491ee1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>541c7fe8-c201-4a53-8420-d3461d6fcfee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formRegister&quot;)/div[@class=&quot;row lang-login-div&quot;]/div[@class=&quot;col-md-12 register-row&quot;]/div[@class=&quot;col-xs-6 have-account-text padding-login-link&quot;]/center[1]/a[@class=&quot;login-link&quot;]</value>
      <webElementGuid>e8eace53-fd20-4a41-9a73-7ddef3ef68be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick=&quot;redirect_overlay('https://stage.mobipaid.com/login')&quot;])[2]</value>
      <webElementGuid>f97fff74-3bc7-492a-a915-29e7fcdc0ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRegister']/div[9]/div/div[2]/center/a</value>
      <webElementGuid>76fd83a1-bba9-4f9c-b138-6ffddc4b69db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Login')])[2]</value>
      <webElementGuid>5f451229-2a3c-42f4-b76d-ea20ea087948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/center/a</value>
      <webElementGuid>f305488b-ec88-4f97-9e5c-881ba0921e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>379b3d2b-9327-4f2e-9bc3-2d41ac2ba45d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
