<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Invalid phone number</name>
   <tag></tag>
   <elementGuidId>0d7aa793-30e0-44fb-a85c-4b605acef1c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#error-mob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='error-mob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>964ca012-a0c6-4c56-a815-499ca7e4ac7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile-alert alert-danger col-md-12 animated fadeInDown</value>
      <webElementGuid>ba2ec707-4d28-410d-8d44-3077c53f3665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>error-mob</value>
      <webElementGuid>3b623ea8-f3cf-4ab1-88b4-e9148f5fff83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid phone number </value>
      <webElementGuid>d6334b36-974f-4df2-a98d-01a444070e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;error-mob&quot;)</value>
      <webElementGuid>382dee45-1ef2-4a01-9753-b81d3de1505f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='error-mob']</value>
      <webElementGuid>213bd3e0-57f2-404e-831e-d2b48a3592f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRegister']/div[2]/div/div</value>
      <webElementGuid>d5765e07-4631-4937-a392-9d1d9f852a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div</value>
      <webElementGuid>7cb05aec-0a11-4c89-9296-307d6d87602a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'error-mob' and (text() = 'Invalid phone number ' or . = 'Invalid phone number ')]</value>
      <webElementGuid>ee01d636-3ba1-4ed9-bc71-76729c0badb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
