<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_company_age</name>
   <tag></tag>
   <elementGuidId>e661bf22-fd8f-424b-b6c3-2123edb40f3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputCompanyAge</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputCompanyAge']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c70dba3b-90c8-45e5-9974-47b8504ee949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>2694146e-60d6-4a7f-beb2-d9a72f26a8bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0a7fe8d5-7320-4a7c-9414-4edaf82fc817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control minor-edit</value>
      <webElementGuid>1c035a9f-ccc2-47d3-b2d2-06f64abe3ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputCompanyAge</value>
      <webElementGuid>cff594e1-ce59-4280-84e3-81d423d3b200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company_age</value>
      <webElementGuid>6a756b85-d859-4337-97d9-3e9316d8f1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputCompanyAge&quot;)</value>
      <webElementGuid>6c9aa189-dcde-42ba-96a4-2b98b4d5afaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputCompanyAge']</value>
      <webElementGuid>deab51a3-d85e-4b6e-b4ac-3e645b40b73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-1']/div[2]/div[17]/div/input</value>
      <webElementGuid>0a3b7f8a-0bda-42db-acce-b3f990cb6547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/input</value>
      <webElementGuid>cddec131-2b2c-40cc-b98e-9c4dde08aa3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputCompanyAge' and @name = 'company_age']</value>
      <webElementGuid>4b8afb78-4d71-43e1-8df0-b890764dc9ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
