<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_signatory_id_number</name>
   <tag></tag>
   <elementGuidId>1851d142-7c67-4cee-83a2-e77fd2fe6bf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputSignatoryIdNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputSignatoryIdNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>134d4780-e672-4182-9608-e8b53dc6670f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>1b9603ad-bb3c-4974-ac31-20af8328ca68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3eae8489-de49-4469-ac86-7ab5110fb672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control minor-edit error</value>
      <webElementGuid>a7447cb6-9287-4a82-997a-52129d302531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputSignatoryIdNumber</value>
      <webElementGuid>c389e2b9-c374-455d-a24f-604238ee3e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signatory_id_number</value>
      <webElementGuid>f41f256e-89a6-4f1d-a3e2-05f9047f3fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputSignatoryIdNumber&quot;)</value>
      <webElementGuid>c3aaa3e8-3afd-4ca9-bf21-f123ef7cd97c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputSignatoryIdNumber']</value>
      <webElementGuid>9cdf6c03-5262-4a16-a562-fce378731a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-2']/div[2]/div[4]/div/input</value>
      <webElementGuid>686800ce-256e-4288-ad81-733fe8894000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>2409f406-ae08-4e39-baf5-3381c50e5cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputSignatoryIdNumber' and @name = 'signatory_id_number']</value>
      <webElementGuid>24a3d332-d254-40f2-ab1c-643cda055274</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
