<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_trading_name</name>
   <tag></tag>
   <elementGuidId>8210c8af-02bb-45b9-9a03-2d109ba975b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_trading_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_trading_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9c31dc2-29c3-46fe-9133-428aa54078ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>963ab35a-5589-4228-af3a-dd1618efa744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>242aa4b2-d878-475d-989b-7ec52e3f65fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control minor-edit</value>
      <webElementGuid>3cf4fc04-dd45-4361-be3e-1f3cad1679fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_trading_name</value>
      <webElementGuid>126520ed-d72f-463b-8dae-1eeb6bce4f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>trading_name</value>
      <webElementGuid>3ba4c8e7-ccdd-4073-b41a-51728803f700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_trading_name&quot;)</value>
      <webElementGuid>da70883a-bc73-4a03-aa71-702927fc4614</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_trading_name']</value>
      <webElementGuid>feef7702-ffde-47bf-af18-4b8960dc7a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-1']/div[2]/div[3]/div/input</value>
      <webElementGuid>237dc23e-d9c5-46a1-9399-7c6e5faf9ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>0b0c1d63-f419-47d3-a265-c607eb889ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input_trading_name' and @name = 'trading_name']</value>
      <webElementGuid>32ac81f8-95d3-48e6-9684-228f50e58aff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
