<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_signatory_email</name>
   <tag></tag>
   <elementGuidId>0e4f384a-852e-4e44-a1ff-6c03896f5254</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputSignatoryEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputSignatoryEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1579a827-43c7-4227-addb-29a88d5aa6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>bf2522a4-05c7-4ecb-982e-09a423af27fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7ebd8b5b-33da-43bd-91aa-a76247e31303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control minor-edit error</value>
      <webElementGuid>4c81aef1-ae63-4bbe-b82e-dc49ef282690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputSignatoryEmail</value>
      <webElementGuid>6f008e42-bf48-4021-9d8d-e62701435ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signatory_email</value>
      <webElementGuid>e28760c2-1bd6-4c85-86e7-19b1e34b178f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputSignatoryEmail&quot;)</value>
      <webElementGuid>40820213-41cb-44fa-a84e-005742f94fdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputSignatoryEmail']</value>
      <webElementGuid>0317eb00-ad5d-4437-85cd-913db53151c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-2']/div[2]/div[3]/div/input</value>
      <webElementGuid>64c474b1-1fcd-4089-a448-4ce0dd9c7c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/div/input</value>
      <webElementGuid>525511c1-6cc2-4ca0-8bb2-ff07751f4215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputSignatoryEmail' and @name = 'signatory_email']</value>
      <webElementGuid>9f6aa5e1-addd-406b-b377-e02be19d06bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
