<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_company_website</name>
   <tag></tag>
   <elementGuidId>b9e43cc2-13d9-4747-8993-2642ac4a5ff6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputCompanyWebsite</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputCompanyWebsite']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55c463d1-3853-43e9-b5d6-d7cf3a8b8de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>752ab5ed-9ebf-4c3e-9935-71bc32e8d929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c12919b5-1cfa-44e0-a984-e54edeb1d87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control minor-edit</value>
      <webElementGuid>d1695dbf-4e83-4992-b40c-2cb88643f6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputCompanyWebsite</value>
      <webElementGuid>5994ce9f-ef44-46aa-a35b-a50e14af6b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company_website</value>
      <webElementGuid>f0772d4e-3a54-4432-a0a2-b83b898328d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputCompanyWebsite&quot;)</value>
      <webElementGuid>e3f293fa-d909-42e4-97a5-8dc2e4190748</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputCompanyWebsite']</value>
      <webElementGuid>6e62cf97-322c-4ad6-80c1-f7f754664e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-1']/div[2]/div[16]/div/input</value>
      <webElementGuid>a7fa9232-312e-4f97-b262-bf4d04d8dc17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/input</value>
      <webElementGuid>bfaa37ef-4382-4c82-bac7-2e468ad522b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputCompanyWebsite' and @name = 'company_website']</value>
      <webElementGuid>611cab94-81bc-4d94-91e4-5401e9558be4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
