<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Facebook                Twitter     _c639f7</name>
   <tag></tag>
   <elementGuidId>de63a446-2b8d-446c-a819-2ef7280681cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#referral_socmed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='referral_socmed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6e062839-6550-4469-95b6-05f0fdde776c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>865cb64e-5508-41b4-8ca6-99abf32545fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>db0ac1f5-b96a-4291-9732-da8a545dc2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>referral_socmed</value>
      <webElementGuid>07a853d8-d65b-4e01-aee2-e930a260bd60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>referral_socmed</value>
      <webElementGuid>9f98e1c0-4ab0-4adc-9191-ad3f124c4ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Facebook
                Twitter
                Linkedin
            </value>
      <webElementGuid>024473d5-910c-4139-a024-c50b9a7e4292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;referral_socmed&quot;)</value>
      <webElementGuid>c263505d-1af2-4282-bf58-f22357cfbff5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='referral_socmed']</value>
      <webElementGuid>8ccc05d8-5ab0-40be-8e22-d41fa33dcdea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-1']/div[2]/div/div[2]/select[2]</value>
      <webElementGuid>464ba2e3-782e-49ca-8585-ce3a9fb47f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>aa9ea97b-502b-45b3-bd6a-4d266072dbc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'referral_socmed' and @name = 'referral_socmed' and (text() = '
                Facebook
                Twitter
                Linkedin
            ' or . = '
                Facebook
                Twitter
                Linkedin
            ')]</value>
      <webElementGuid>1157b4da-8762-44b4-8e2b-dd08fc88a99e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
