<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_company_desc</name>
   <tag></tag>
   <elementGuidId>71514ff8-302c-4d88-90d1-fa43d78e50be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_company_desc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input_company_desc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8ecc7893-57df-419a-8e1b-e5b33443463b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>c2cf6135-cca8-497c-a58b-0cca481acc1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>91f30899-572a-4029-b174-b73f49b477c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>de618f51-8731-42fd-b87a-d1e596c76f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control minor-edit no-resize error</value>
      <webElementGuid>99087583-be38-4c4b-898d-6d509de2f534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_company_desc</value>
      <webElementGuid>998f346e-761c-49fd-bd94-1e25364ec243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company_desc</value>
      <webElementGuid>1b92192f-86f7-42fc-b8b5-967caac7b442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_company_desc&quot;)</value>
      <webElementGuid>15e590f4-d164-4169-84b6-6785bfdef052</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input_company_desc']</value>
      <webElementGuid>a3fe626c-3406-4c54-8cc3-77a80a294d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-1']/div[2]/div[5]/div/textarea</value>
      <webElementGuid>b5c1183c-2b1a-408a-88c2-3f2d5d37618d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>29d2e4fb-171c-4c2a-8118-e6babe2131df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input_company_desc' and @name = 'company_desc']</value>
      <webElementGuid>eb2079eb-04f5-4aa5-92c7-03d5276d753d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
